### ISSUE TITLE
Tabbouleh 1.0.0

### ISSUE THREAD

**Issue by Chnapy** [Chnapy/tabbouleh#39]
What remains to be done before the first stable version.

- [x] Add JSONArray #38
- [x] References #32 
  - [x] FIX circular reference #36 
  - [x] Rename association to reference #48 
- [x] Dependencies up to date #30 
- [x] Refactor tests #35 
- [x] Test coverage 100%
- [x] Edit Travis config to remove auto release
- [x] Comment
- [x] Improve docs #37
